[Running] python "c:\Users\ccadenc\Desktop\pythonstuff\Car\car.py"
    File "c:\Users\ccadenc\Desktop\pythonstuff\Car\car.py", line 2
        def __init__(self, price, speed, fuel, mileage)
            ^
SyntaxError: invalid syntax

[Done] exited with code = 1 in 0.155 seconds

[Running] python "c:\Users\ccadenc\Desktop\pythonstuff\Car\car.py"
Traceback(most recent call last):
    File "c:\Users\ccadenc\Desktop\pythonstuff\Car\car.py", line 22, in < module >
        car1 = Car(5000, 8, "Full", 30)
    File "c:\Users\ccadenc\Desktop\pythonstuff\Car\car.py", line 11, in __init__
        self.milleage = milleage
NameError: global name 'milleage' is not defined

[Done] exited with code = 1 in 0.273 seconds

[Running] python "c:\Users\ccadenc\Desktop\pythonstuff\Car\car.py"
Price: 5000
Speed: 8mph
Fuel: Full
Mileage: 30mpg
Tax0.12
Price: 3000
Speed: 20mph
Fuel: Halfway
Mileage: 28mpg
Tax0.12

[Done] exited with code = 0 in 0.123 seconds

[Running] python "c:\Users\ccadenc\Desktop\pythonstuff\Product\Product.py"
    File "c:\Users\ccadenc\Desktop\pythonstuff\Product\Product.py", line 1
        class Proudct(object)
            ^
SyntaxError: invalid syntax

[Done] exited with code = 1 in 0.105 seconds

[Running] python "c:\Users\ccadenc\Desktop\pythonstuff\Product\Product.py"
    File "c:\Users\ccadenc\Desktop\pythonstuff\Product\Product.py", line 11
        def display_all(self):
        ^
IndentationError: unexpected indent

[Done] exited with code = 1 in 0.117 seconds

[Running] python "c:\Users\ccadenc\Desktop\pythonstuff\Product\Product.py"
Traceback(most recent call last):
    File "c:\Users\ccadenc\Desktop\pythonstuff\Product\Product.py", line 20, in < module >
        item1 = Product(50, "pile of cards", 2, "squigly brand", 2)
NameError: name 'Product' is not defined

[Done] exited with code = 1 in 0.146 seconds

[Running] python "c:\Users\ccadenc\Desktop\pythonstuff\Product\Product.py"
Traceback(most recent call last):
    File "c:\Users\ccadenc\Desktop\pythonstuff\Product\Product.py", line 20, in < module >
        item1 = Product(50, "pile of cards", 2, "squigly brand", 2)
    File "c:\Users\ccadenc\Desktop\pythonstuff\Product\Product.py", line 3, in __init__
        self.price = price
NameError: global name 'self' is not defined

[Done] exited with code = 1 in 0.161 seconds

[Running] python "c:\Users\ccadenc\Desktop\pythonstuff\Product\Product.py"
Traceback(most recent call last):
    File "c:\Users\ccadenc\Desktop\pythonstuff\Product\Product.py", line 20, in < module >
        item1 = Product(50, "pile of cards", 2, "squigly brand", 2)
TypeError: __init__() takes exactly 7 arguments(6 given)

[Done] exited with code = 1 in 0.121 seconds

[Running] python "c:\Users\ccadenc\Desktop\pythonstuff\Product\Product.py"
Traceback(most recent call last):
    File "c:\Users\ccadenc\Desktop\pythonstuff\Product\Product.py", line 20, in < module >
        item1 = Product(50, "pile of cards", 2, "squigly brand", 2)
TypeError: __init__() takes exactly 7 arguments(6 given)

[Done] exited with code = 1 in 0.106 seconds

[Running] python "c:\Users\ccadenc\Desktop\pythonstuff\Product\Product.py"
Traceback(most recent call last):
    File "c:\Users\ccadenc\Desktop\pythonstuff\Product\Product.py", line 20, in < module >
        item1 = Product(50, "pile of cards", 2,
                        "squigly brand", 2, self.status)
NameError: name 'self' is not defined

[Done] exited with code = 1 in 0.128 seconds

[Running] python "c:\Users\ccadenc\Desktop\pythonstuff\Product\Product.py"

[Done] exited with code = 0 in 0.086 seconds

[Running] python "c:\Users\ccadenc\Desktop\pythonstuff\Product\Product.py"

[Done] exited with code = 0 in 0.088 seconds

[Running] python "c:\Users\ccadenc\Desktop\pythonstuff\Product\Product.py"

[Done] exited with code = 0 in 0.1 seconds

[Running] python "c:\Users\ccadenc\Desktop\pythonstuff\Product\Product.py"
Traceback(most recent call last):
    File "c:\Users\ccadenc\Desktop\pythonstuff\Product\Product.py", line 19, in < module >
        item1 = Product(50, "pile of cards", 2, "squigly brand", "for sale")
TypeError: __init__() takes exactly 7 arguments(6 given)

[Done] exited with code = 1 in 0.1 seconds

[Running] python "c:\Users\ccadenc\Desktop\pythonstuff\Product\Product.py"
    File "c:\Users\ccadenc\Desktop\pythonstuff\Product\Product.py", line 24
        self.status = "used"
        ^
IndentationError: unexpected indent

[Done] exited with code = 1 in 0.107 seconds

[Running] python "c:\Users\ccadenc\Desktop\pythonstuff\Product\Product.py"
    File "c:\Users\ccadenc\Desktop\pythonstuff\Product\Product.py", line 23
        elif(reason == "opened")
            ^
SyntaxError: invalid syntax

[Done] exited with code = 1 in 0.093 seconds

[Running] python "c:\Users\ccadenc\Desktop\pythonstuff\Product\Product.py"
    File "c:\Users\ccadenc\Desktop\pythonstuff\Product\Product.py", line 23
        elif(reason == "opened")
            ^
SyntaxError: invalid syntax

[Done] exited with code = 1 in 0.113 seconds

[Running] python "c:\Users\ccadenc\Desktop\pythonstuff\Product\Product.py"
    File "c:\Users\ccadenc\Desktop\pythonstuff\Product\Product.py", line 33
        print "Status": "{}".format(self.status)
            ^
SyntaxError: invalid syntax

[Done] exited with code = 1 in 0.092 seconds

[Running] python "c:\Users\ccadenc\Desktop\pythonstuff\Product\Product.py"
Traceback(most recent call last):
    File "c:\Users\ccadenc\Desktop\pythonstuff\Product\Product.py", line 38, in < module >
        item1 = Product(50, "pile of cards", 2, "squigly brand", "for sale")
TypeError: __init__() takes exactly 7 arguments(6 given)

[Done] exited with code = 1 in 0.121 seconds

[Running] python "c:\Users\ccadenc\Desktop\pythonstuff\Product\Product.py"
Traceback(most recent call last):
    File "c:\Users\ccadenc\Desktop\pythonstuff\Product\Product.py", line 38, in < module >
        item1 = Product(50.50, "gold plated pile of cards", 2, "squigly brand")
TypeError: __init__() takes exactly 7 arguments(5 given)

[Done] exited with code = 1 in 0.1 seconds

[Running] python "c:\Users\ccadenc\Desktop\pythonstuff\Product\Product.py"
Traceback(most recent call last):
    File "c:\Users\ccadenc\Desktop\pythonstuff\Product\Product.py", line 38, in < module >
        item1 = Product(50.50, "gold plated pile of cards", 2, "squigly brand")
TypeError: __init__() takes exactly 6 arguments(5 given)

[Done] exited with code = 1 in 0.103 seconds

[Running] python "c:\Users\ccadenc\Desktop\pythonstuff\Product\Product.py"

[Done] exited with code = 0 in 0.098 seconds

[Running] python "c:\Users\ccadenc\Desktop\pythonstuff\Product\Product.py"

[Done] exited with code = 0 in 0.105 seconds

[Running] python "c:\Users\ccadenc\Desktop\pythonstuff\Product\Product.py"
<__main__.Product object at 0x00000000024E9DD8 >

[Done] exited with code = 0 in 0.11 seconds

[Running] python "c:\Users\ccadenc\Desktop\pythonstuff\Product\Product.py"
    File "c:\Users\ccadenc\Desktop\pythonstuff\Product\Product.py", line 39
        item1.display_all()
        ^
IndentationError: unexpected indent

[Done] exited with code = 1 in 0.11 seconds

[Running] python "c:\Users\ccadenc\Desktop\pythonstuff\Product\Product.py"
Traceback(most recent call last):
    File "c:\Users\ccadenc\Desktop\pythonstuff\Product\Product.py", line 39, in < module >
        item1.display_all()
AttributeError: 'Product' object has no attribute 'display_all'

[Done] exited with code = 1 in 0.113 seconds

[Running] python "c:\Users\ccadenc\Desktop\pythonstuff\Product\Product.py"
Traceback(most recent call last):
    File "c:\Users\ccadenc\Desktop\pythonstuff\Product\Product.py", line 39, in < module >
        display_all()
NameError: name 'display_all' is not defined

[Done] exited with code = 1 in 0.108 seconds

[Running] python "c:\Users\ccadenc\Desktop\pythonstuff\Product\Product.py"
Traceback(most recent call last):
    File "c:\Users\ccadenc\Desktop\pythonstuff\Product\Product.py", line 39, in < module >
        item1.display_all()
AttributeError: 'Product' object has no attribute 'display_all'

[Done] exited with code = 1 in 0.11 seconds

[Running] python "c:\Users\ccadenc\Desktop\pythonstuff\Product\Product.py"
Price: 50.5 USD
item name: gold plated pile of cards
weight: 2 oz
brand: squigly brand
Status: for sale
~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*

[Done] exited with code = 0 in 0.097 seconds

[Running] python "c:\Users\ccadenc\Desktop\pythonstuff\Product\Product.py"
Traceback(most recent call last):
    File "c:\Users\ccadenc\Desktop\pythonstuff\Product\Product.py", line 40, in < module >
        p2.return_product("defective").display_all()
NameError: name 'p2' is not defined

[Done] exited with code = 1 in 0.114 seconds

[Running] python "c:\Users\ccadenc\Desktop\pythonstuff\Product\Product.py"
Traceback(most recent call last):
    File "c:\Users\ccadenc\Desktop\pythonstuff\Product\Product.py", line 40, in < module >
        p2.return_product("defective").display_all()
NameError: name 'p2' is not defined

[Done] exited with code = 1 in 0.107 seconds

[Running] python "c:\Users\ccadenc\Desktop\pythonstuff\Product\Product.py"
Price: 0 USD
item name: jewelry tree
weight: 3 oz
brand: blingbling brand
Status: Defective
~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*
Price: 50.5 USD
item name: gold plated pile of cards
weight: 2 oz
brand: squigly brand
Status: for sale
~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*

[Done] exited with code = 0 in 0.099 seconds

[Running] python "c:\Users\ccadenc\Desktop\pythonstuff\Animals\Animals.py"
    File "c:\Users\ccadenc\Desktop\pythonstuff\Animals\Animals.py", line 6
        def walk(self):
            ^
IndentationError: unindent does not match any outer indentation level

[Done] exited with code = 1 in 0.097 seconds

[Running] python "c:\Users\ccadenc\Desktop\pythonstuff\Animals\Animals.py"
    File "c:\Users\ccadenc\Desktop\pythonstuff\Animals\Animals.py", line 22
        class Rabbit (Animal):
        ^
IndentationError: unexpected indent

[Done] exited with code = 1 in 0.101 seconds

[Running] python "c:\Users\ccadenc\Desktop\pythonstuff\Animals\Animals.py"
    File "c:\Users\ccadenc\Desktop\pythonstuff\Animals\Animals.py", line 32
        r1 = Rabbit(Cinnabun):
            ^
SyntaxError: invalid syntax

[Done] exited with code = 1 in 0.099 seconds

[Running] python "c:\Users\ccadenc\Desktop\pythonstuff\Animals\Animals.py"
Traceback(most recent call last):
    File "c:\Users\ccadenc\Desktop\pythonstuff\Animals\Animals.py", line 1, in < module >
        class Animals(object):
    File "c:\Users\ccadenc\Desktop\pythonstuff\Animals\Animals.py", line 19, in Animals
        c = a1 = Animal("Fluffy")
NameError: name 'Animal' is not defined

[Done] exited with code = 1 in 0.1 seconds

[Running] python "c:\Users\ccadenc\Desktop\pythonstuff\Animals\Animals.py"
Traceback(most recent call last):
    File "c:\Users\ccadenc\Desktop\pythonstuff\Animals\Animals.py", line 1, in < module >
        class Animal(object):
    File "c:\Users\ccadenc\Desktop\pythonstuff\Animals\Animals.py", line 19, in Animal
        c = a1 = Animal("Fluffy")
NameError: name 'Animal' is not defined

[Done] exited with code = 1 in 0.094 seconds

[Running] python "c:\Users\ccadenc\Desktop\pythonstuff\Animals\Animals.py"
Traceback(most recent call last):
    File "c:\Users\ccadenc\Desktop\pythonstuff\Animals\Animals.py", line 1, in < module >
        class Animal(object):
    File "c:\Users\ccadenc\Desktop\pythonstuff\Animals\Animals.py", line 19, in Animal
        a1 = Animal("Fluffy")
NameError: name 'Animal' is not defined

[Done] exited with code = 1 in 0.104 seconds

[Running] python "c:\Users\ccadenc\Desktop\pythonstuff\Animals\Animals.py"
Traceback(most recent call last):
    File "c:\Users\ccadenc\Desktop\pythonstuff\Animals\Animals.py", line 1, in < module >
        class Animal(object):
    File "c:\Users\ccadenc\Desktop\pythonstuff\Animals\Animals.py", line 19, in Animal
        a1 = Animal("Fluffy")
NameError: name 'Animal' is not defined

[Done] exited with code = 1 in 0.133 seconds

[Running] python "c:\Users\ccadenc\Desktop\pythonstuff\Animals\Animals.py"
    File "c:\Users\ccadenc\Desktop\pythonstuff\Animals\Animals.py", line 22
        class Rabbit (Animal):
        ^
IndentationError: unexpected indent

[Done] exited with code = 1 in 0.098 seconds

[Running] python "c:\Users\ccadenc\Desktop\pythonstuff\Animals\Animals.py"
Traceback(most recent call last):
    File "c:\Users\ccadenc\Desktop\pythonstuff\Animals\Animals.py", line 19, in < module >
        a1 = Animal("Fluffy")
TypeError: __init__() takes exactly 3 arguments(2 given)

[Done] exited with code = 1 in 0.133 seconds

[Running] python "c:\Users\ccadenc\Desktop\pythonstuff\Animals\Animals.py"
Health 87
Traceback(most recent call last):
    File "c:\Users\ccadenc\Desktop\pythonstuff\Animals\Animals.py", line 34, in < module >
        r1 = Rabbit(Cinnabun)
NameError: name 'Cinnabun' is not defined

[Done] exited with code = 1 in 0.094 seconds

[Running] python "c:\Users\ccadenc\Desktop\pythonstuff\Animals\Animals.py"
Health 87
Traceback(most recent call last):
    File "c:\Users\ccadenc\Desktop\pythonstuff\Animals\Animals.py", line 35, in < module >
        r1 = Rabbit("Cinnabun", 500)
TypeError: __init__() takes exactly 2 arguments(3 given)

[Done] exited with code = 1 in 0.093 seconds

[Running] python "c:\Users\ccadenc\Desktop\pythonstuff\Animals\Animals.py"
Health 87
Traceback(most recent call last):
    File "c:\Users\ccadenc\Desktop\pythonstuff\Animals\Animals.py", line 35, in < module >
        r1 = Rabbit("Cinnabun")
    File "c:\Users\ccadenc\Desktop\pythonstuff\Animals\Animals.py", line 27, in __init__
        super(Rabbit, self).__init__(name)
TypeError: __init__() takes exactly 3 arguments(2 given)

[Done] exited with code = 1 in 0.098 seconds
